### ISSUE TITLE
Archlinux support

### ISSUE THREAD

**Issue by Matthewxx** [clownix/cloonix#1]
Hello,
Can you add the Archlinux support?

```
sudo ./install_depends build

	Packages to build cloonix will be installed.


	ERROR: Your distribution: Arch is not supported
	You must install the packages by hand.
```

**Comment by clownix** [comment]
Sorry about that, I do not have the time to check all the distributions.
Debian, Ubuntu, Fedora, Centos and Opensuse are the only supported ones.
