### ISSUE TITLE
Cannot ssh into guest vm

### ISSUE THREAD

**Issue by kilisio** [clownix/cloonix#1]
I am trying to ssh into the cloonix client using the config below using the openwrt image provided:
```bash
#!/bin/bash
NET=nemo
DIST=openwrt
VM=openwrt

# start nemo cloonix server
is_started=$(cloonix_cli $NET pid | grep cloonix_server)
if [ "x$is_started" == "x" ]; then
  printf "\nServer Not started, launching:"
  printf "\ncloonix_net $NET:\n"
  cloonix_net $NET
else
  cloonix_cli $NET rma
fi

echo waiting 2 sec
sleep 2

# start cloonix gui viewer
cloonix_gui $NET

# add virtual machine images
cloonix_cli $NET add kvm ${VM} ram=512 cpu=1 eth=s ${DIST}.qcow2 --persistent & 

sleep 2

# setup nat and wireshark 
cloonix_cli $NET add lan ${VM} 0 lan
cloonix_cli $NET add nat nat
cloonix_cli $NET add snf snf
cloonix_cli $NET add lan nat 0 lan
cloonix_cli $NET add lan snf 0 lan

cloonix_ice $NET $VM &

```

After it finishes booting up i run:

> cloonix_ssh nemo openwrt

to test ssh, but it gives me the message

> NOT REACHABLE: openwrt

I also tired editing /etc/config/dropbear in the openwrt guest image to disable password authentication, but i still get the same message. Kindly assist. Also thank you for this amazing package

**Comment by clownix** [comment]
Sorry for the late response, I forgot to look at github for a few days...
For the openwrt to get the reacheability with cloonix, there must be the following line in /etc/inittab:

cat /etc/inittab
...
hvc0::askfirst:/usr/libexec/login.sh
...
This line permits the entering and execution in the guest of the /tmp/dropbear_cloonix_agent.sh file.
To debug, you must check that the hvc0 line exists, and if so, that /tmp/dropbear_cloonix_agent.sh exists, and if so, that this file can be executed with no error.
