### ISSUE TITLE
Instruction for building from source

### ISSUE THREAD

**Issue by bastien-roucaries** [clownix/cloonix#11]
Hi,

I want to package this under debian if you want

Can you give me instruction for building from source

Bastien

**Comment by clownix** [comment]
First you have to go to cloonix_xx/quickstart/kvm_create/ and call the bookworm script to create bookworm.qcow2 (or download it). This creates the "/var/lib/cloonix/bulk/bookworm.qcow2".

Then you have to go to cloonix_xx/build_tools/vmbuild/ put a goot REPO in vmbuild_create and call vmbuild_create to get the debian machine in which the compile is done. The  vmbuild_create copies the bookworm.qcow2 and does some apt-gets to create the "/var/lib/cloonix/bulk/debian_builder.qcow2".

Then your main cloonix tree repo must be called sources: "mv cloonix_xx/ sources".

Then go to sources/build_tools/vmbuild/ and call ./doitall.

The doitall tars the sources directory, transfers it into the debian_builder and builds the bundle in the debian_builder.
Then you finally get the bundle in sources/build_tools/.

I would be very happy if you can create a debian package:) Thanks for that and if you need changes I am at your service:)

**Comment by bastien-roucaries** [comment]
Hi

For debian packaging the  cloonix_xx/quickstart/kvm_create/  will not be needed we are on bare metal... 

So it is a list of depends we need

**Comment by clownix** [comment]
Inside the script that constructs the vm used for the building there is the apt-get that pulls all necessary packages to build.
see in cloonix_xx/ build_tools/vmbuild/vmbuild_create for the packages.
But cloonix is not a simple thing to packages, wireshark is pre-built so as to  avoid problems.
Also, there are sources compiled that come from git and stored inside the targz_store... Not a simple task to create a package!

**Comment by bastien-roucaries** [comment]
Can we get piece per piece the stuff ?

I will like to package some easy stuff first, thus we could do the work.

Why do you need prebuilt wireshark ?

**Comment by clownix** [comment]
I wanted a wireshark ready within cloonix and it is long to compile, so I do it once separately and it stays in targz_store.
To get a usable package with cloonix, there is work to do. For example I would have to call the official wireshark, but as I have put patches in this software, it is not so simple. See in targz_store/shark_qt/wireshark.patch for the patch.
And also I compile ovs and qemu-kvm and spice, this should be avoided for a packaged cloonix...
I think that next year would be the right time for this work, I will try to work towards this goal little by little...

**Comment by bastien-roucaries** [comment]
@clownix I could help here if needed.

**Comment by clownix** [comment]
For the moment the effort is on the standalone product, perhaps next year the integration into a distribution will be started...

**Comment by bastien-roucaries** [comment]
@clownix may be your patch are interesting for debian... So just documenting I can maybe merge
