### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by s-c-p** [clownix/cloonix#12]
Hi,

Please specify which license is it using - we'd like to add it to Nix packages.

Thanks.

**Comment by clownix** [comment]
It is GPLv3 but it is not at all easy to include it in a package, it is a bundle of many open-sources that are more or less patched.
I am not sure what license can be applied to a mix of so many open-sources... My personal code is the cement, coded with the gplv3 but the main actors are not mine.  My current aim is to provide a bundle that is installable on any linux distribution but not packaged ... The software is not yet mature enough to be packaged. Too soon, next year will be ok.
