### ISSUE TITLE
Waiting for stuff to complete

### ISSUE THREAD

**Issue by Arseny-N** [clownix/cloonix#2]
Hi, I've tried to use cloonix for a while, and the overall experience was OK, but a recurring theme in your example bash scripts is waiting for a program to complete. You use sleeping, but bash has a built in called `wait` which waits for child processes, it seams more appropriate. 

I am not very experienced with qemu and neworks, so couldn't you explain if there is a particular reason you use sleep ?

**Comment by clownix** [comment]
Sorry about the delay, I do not look at the github often enough. 
Where exactly is the sleep you are speaking about ? What file ?
Regards
Vincent
