### ISSUE TITLE
Mikrotik RouterOS

### ISSUE THREAD

**Issue by kilisio** [clownix/cloonix#2]
I am currently trying to simulate a network using Mikrotik's cloud hosted RouterOS
```
https://download.mikrotik.com/routeros/6.48.1/chr-6.48.1.img.zip
```
I successfully converted it to a qemu image `qcow2`, but when i run it on cloonix it freezes while loading.
When I run it on qemu without cloonix, it loads properly. 
I am currently using cloonix version 14.0.0.
Could this be a Qemu version issue?

**Comment by clownix** [comment]
Sorry kilisio, I just saw your problem, it does not work for me either but it is not qemu, it has to do with the configuration of qemu done in cloonix... I do not have time now but I will look into it at the beginning of may 2021.
Mikritik router seems to be very special, when you do the following linux commands:

losetup /dev/loop0 /root/chr-6.48.1.img
losetup -o 512 /dev/loop1 /dev/loop0
mount /dev/loop1 /root/mnt/
find /root/mnt/

You see that it is not a usual machine, I have to work on the subject to try and make it work...
Sorry for the delay.

**Comment by clownix** [comment]
You must use the v16-00 for the Mikrotik, the use is similar to the cisco c8000v use within cloonix, nobackdoor and natplug options are used, see tools/cisco and tools/mikrotik for examples.
Thanks for this issue.
For next issue, please send a mail to clownix@clownix.net for faster correction.

**Comment by kilisio** [comment]
Apologies for late feedback. It now works like a charm. I shall keep testing it as i try create a mesh network. Thank you for the quick fix.

**Comment by clownix** [comment]
You are very kind to speak of "quick fix", it took 15 days before I saw 
your issue, then 15 more days before the fix:)

Thanks for the mikrotik info, if there is another router you wish to 
use, tell me, I did not know about mikrotik and I was pleased to make it 
work in cloonix.

Regards

Vincent Perrier

Le 09.05.2021 09:52, kilisio a écrit :

> Apologies for late feedback. It now works like a charm. I shall keep 
> testing it as i try create a mesh network. Thank you for the quick fix.
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].



Links:
------
[1] https://github.com/clownix/cloonix/issues/2#issuecomment-835732697
[2]

**Comment by kilisio** [comment]
Sometimes opened issues in other repositories never get answered and given that the inner workings of cloonix is frankly still a mystery to me, the least I can do is be patient, furthermore one month is not that long a wait given that we all have other things occupying our time. Am currently using mikrotik for a small personal project and thought it would be fun to simulate and test its api and modules before i went ahead and bought their routers. If i do find another router/network operating system that require attention i shall put up an issue request.

I would like to reopen this issue briefly. I just updated my operating system:

```bash
    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.2 LTS
    Release:	20.04
    Codename:	focal
```
and now i keep getting this error: 
> ERROR QEMU UNEXPECTED STOP

when i check my /var/log/syslog it shows this error:
> May  9 22:31:24 kilisio qemu-system-x86_64: qemu_log_func line:401 GLib: ../../../glib/gmem.c:138: failed to allocate 18446744073709551608 bytes

I have tried re-building cloonix but I get the same error. I have reinstalled and tried an older cloonix version and it works just fine. Any way I could resolve this issue?

> $ cat /proc/meminfo

```bash
MemTotal:        8082472 kB
MemFree:          140716 kB
MemAvailable:    1604868 kB
Buffers:          197932 kB
Cached:          1681192 kB
SwapCached:        16484 kB
Active:          1733696 kB
Inactive:        1567724 kB
Active(anon):    1027624 kB
Inactive(anon):   674740 kB
Active(file):     706072 kB
Inactive(file):   892984 kB
Unevictable:       45728 kB
Mlocked:              32 kB
SwapTotal:       3969020 kB
SwapFree:        3756284 kB
Dirty:               784 kB
Writeback:             0 kB
AnonPages:       1458484 kB
Mapped:           265240 kB
Shmem:            284844 kB
KReclaimable:     142172 kB
Slab:             289084 kB
SReclaimable:     142172 kB
SUnreclaim:       146912 kB
KernelStack:       12112 kB
PageTables:        20444 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     5913104 kB
Committed_AS:    5782884 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       34208 kB
VmallocChunk:          0 kB
Percpu:             6848 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       4
HugePages_Free:        3
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB
Hugetlb:         4194304 kB
DirectMap4k:      282944 kB
DirectMap2M:     3842048 kB
DirectMap1G:     5242880 kB
```

**Comment by clownix** [comment]
Tomorow I will try to get the same bug you have, I will try the mikrotik 
vm in an ubuntu 20.04.

Usualy I try mikrotik on my debian buster...

2 questions: are you using last cloonix (v16) and are you sure that you 
have launched your mikrotik with "--nobackdoor --natplug=0" ?

Example:

cloonix_cli nemo add kvm mikro  ram=2000 cpu=4 eth=ddd mikro.qcow2 
--nobackdoor --natplug=0

This question because I have had the same kind of strange error when I 
launched mikrotik with a cloonix backdoor.

Note that the backdoor is the nominal use but works only for linux 
guests where we can be root on the guest.

I will send a mail after a try of your setup to tell you if I succeed in 
having the problem.

Regards

Le 09.05.2021 22:09, kilisio a écrit :

> Sometimes opened issues in other repositories never get answered and 
> given that the inner workings of cloonix is frankly still a mystery to 
> me, the least I can do is be patient, furthermore one month is not that 
> long a wait given that we all have other things occupying our time. Am 
> currently using mikrotik for a small personal project and thought it 
> would be fun to simulate and test its api and modules before i went 
> ahead and bought their routers. If i do find another router/network 
> operating system that require attention i shall put up an issue 
> request.
> 
> I would like to reopen this issue briefly. I just updated my operating 
> system:
> 
> Distributor ID:    Ubuntu
> Description:    Ubuntu 20.04.2 LTS
> Release:    20.04
> Codename:    focal
> 
> and now i keep getting this error:
> 
>> ERROR QEMU UNEXPECTED STOP
> 
> when i check my /var/log/syslog it shows this error:
> 
>> May 9 22:31:24 kilisio qemu-system-x86_64: qemu_log_func line:401 
>> GLib: ../../../glib/gmem.c:138: failed to allocate 
>> 18446744073709551608 bytes
> 
> I have tried re-building cloonix but I get the same error. I have 
> reinstalled and tried an older cloonix version and it works just fine. 
> Any way I could resolve this issue?
> 
>> $ cat /proc/meminfo
> 
> MemTotal:        8082472 kB
> MemFree:          140716 kB
> MemAvailable:    1604868 kB
> Buffers:          197932 kB
> Cached:          1681192 kB
> SwapCached:        16484 kB
> Active:          1733696 kB
> Inactive:        1567724 kB
> Active(anon):    1027624 kB
> Inactive(anon):   674740 kB
> Active(file):     706072 kB
> Inactive(file):   892984 kB
> Unevictable:       45728 kB
> Mlocked:              32 kB
> SwapTotal:       3969020 kB
> SwapFree:        3756284 kB
> Dirty:               784 kB
> Writeback:             0 kB
> AnonPages:       1458484 kB
> Mapped:           265240 kB
> Shmem:            284844 kB
> KReclaimable:     142172 kB
> Slab:             289084 kB
> SReclaimable:     142172 kB
> SUnreclaim:       146912 kB
> KernelStack:       12112 kB
> PageTables:        20444 kB
> NFS_Unstable:          0 kB
> Bounce:                0 kB
> WritebackTmp:          0 kB
> CommitLimit:     5913104 kB
> Committed_AS:    5782884 kB
> VmallocTotal:   34359738367 kB
> VmallocUsed:       34208 kB
> VmallocChunk:          0 kB
> Percpu:             6848 kB
> HardwareCorrupted:     0 kB
> AnonHugePages:         0 kB
> ShmemHugePages:        0 kB
> ShmemPmdMapped:        0 kB
> FileHugePages:         0 kB
> FilePmdMapped:         0 kB
> CmaTotal:              0 kB
> CmaFree:               0 kB
> HugePages_Total:       4
> HugePages_Free:        3
> HugePages_Rsvd:        0
> HugePages_Surp:        0
> Hugepagesize:    1048576 kB
> Hugetlb:         4194304 kB
> DirectMap4k:      282944 kB
> DirectMap2M:     3842048 kB
> DirectMap1G:     5242880 kB
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].



Links:
------
[1] https://github.com/clownix/cloonix/issues/2#issuecomment-835877341
[2]

**Comment by kilisio** [comment]
yes i did use the `--nobackdoor` and `--natplug=0` arguments and it was the latest v16. I also tried to simulate an `alpine linux` and `openwrt` VMs without the arguments using the v16, but also got the same error.

**Comment by clownix** [comment]
I cannot reproduce for the moment but I have seen it in the past, too 
bad I did not look into it...

Can you try with a buster.qcow2 that you can download from clownix.net? 
To see if it works...

Le 10.05.2021 06:27, kilisio a écrit :

> yes i did use the --nobackdoor and --natplug=0 arguments and it was the 
> latest v16. I also tried to simulate an alpine linux and openwrt VMs 
> without the arguments using the v16, but also got the same error.
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].



Links:
------
[1] https://github.com/clownix/cloonix/issues/2#issuecomment-836152074
[2]

**Comment by clownix** [comment]
I have installed the ubuntu 20.04 on a PC, updated it, and then 
installed the cloonix depends, compiled cloonix and I still cannot 
reproduce the bug, it works well on this ubuntu 20.4...

Could you update your ubuntu, then recompile cloonix, may-be it will 
work ...

Le 10.05.2021 06:27, kilisio a écrit :

> yes i did use the --nobackdoor and --natplug=0 arguments and it was the 
> latest v16. I also tried to simulate an alpine linux and openwrt VMs 
> without the arguments using the v16, but also got the same error.
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].



Links:
------
[1] https://github.com/clownix/cloonix/issues/2#issuecomment-836152074
[2]

**Comment by kilisio** [comment]
It might not be a bug related with cloonix then. Let me try re-updating my operating system. If it does not work I will try a fresh ubuntu install before recompiling.

**Comment by clownix** [comment]
New version v17-00 to try.

**Comment by kilisio** [comment]
> New version v17-00 to try.

Apologies, I have been a bit busy of late. Let me try the new version and give you feedback. Thank you.
