### ISSUE TITLE
VM nor reachable

### ISSUE THREAD

**Issue by kubasienki** [clownix/cloonix#3]
Hi, 
all of demo scripts hangs on:

> NOT REACHABLE: one
> one not ready, waiting 3 sec

looped to infinity.

When I do all by hand, command cloonix_ssh returns VM not reachable.

Also when I click on vm in graph mode, select term - I can login and work on machine.
I'd setup ping between machines. In local lan it works, but when pinging through the nat to outside world pinging request works, but no return is shown. What is even more strange - dns works. 

Versions from github and site.

**Comment by clownix** [comment]
dns can go from guest to outside with an address translation of the name server. Inside a cloonix guest you see "nameserver 172.17.0.3" in /etc/resolv.conf but in your host you see something like:  "nameserver 192.168.1.254" in /etc/resolv.conf. The cloonix "nat" component translates from one address to the other and the dns message carried by udp can be produced by the nat, go to its target and come back.
ICMP for pings need more priviledges than udp, so pings cannot be produced by the nat component it is sad but pings cannot escape the virtual network without giving priviledges to nat (I do not want that).
For the bugs "not reacheable", I do not reproduce it now, I may have had it in the past.
Thanks for reporting.

**Comment by clownix** [comment]
Another thing, udp works from guest to www outside, ping does not work because of the permissions necessary to open an icmp socket  but the most important protocol TCP works, so you can wget, ssh, ftp, http... from guests to www.
