### ISSUE TITLE
vlan support

### ISSUE THREAD

**Issue by joaohf** [clownix/cloonix#3]
Hello there.

Does cloonix support some sort of switch vlan configuration ? Like this: https://docs.openvswitch.org/en/latest/faq/vlan/

Thanks

**Comment by clownix** [comment]
No, but cloonix sends commands to openvswitch, the vlan commands could be added.
I do not know the exact need for this, if there are particular ovs commands that could be usefull in cloonix, you can explain your need, if it is easy to do I can do it...
