### ISSUE TITLE
ERROR 18 WHILE CREATION

### ISSUE THREAD

**Issue by WladimirDelaCadena** [clownix/cloonix#4]
I tested cloonix in one machine successfully but I want to try running it in another with Ubuntu Linux (release 16.04 LTS server). Cloonix seems to be correct installed but I receive the error 18 ehan I want to create the downloaded vm. I have tried with several vm and the problem is still there.

**Comment by clownix** [comment]
You should test the qemu binary compiled by cloonix in a standalone fashion:
Get a vm, in my case I called it rootfs.qcow2, then
First:
export LD_LIBRARY_PATH="/usr/local/bin/cloonix/common/spice/spice_lib"

Then:
/usr/local/bin/cloonix/server/qemu/qemu_bin/qemu-system-x86_64 -L /usr/local/bin/cloonix/server/qemu/qemu_bin -hda rootfs.qcow2 -nographic -serial=stdio

If this starts, then the qemu works, if not, I hope you get an error message.
