### ISSUE TITLE
Physical interface

### ISSUE THREAD

**Issue by kilisio** [clownix/cloonix#4]
Hello... How do I add a physical interface in version 24-00. What i have tried is:

```bash
     cloonix_cli nemo add phy eth0
```
also I cannot seem to be able to hide nor move the created nat interfaces using:

```bash
    # hiding nat interface
    cloonix_cli nemo cnf lay hide_sat nat1 1

    # manually moving nat interface
    cloonix_cli nemo cnf lay abs_xy_sat nat2 410 382
```

**Comment by clownix** [comment]
For the physical interface, it is better to put a tap and bridge it to the physical interface outside of cloonix with brctl or ovs.
For the hidden sat, I will look at bugs during september, sorry for the delay.
Same for the moving of the nat...
There was so many changes to take out dpdk that there are small regressions, sorry...
On the long term all those will be solved:)

**Comment by kilisio** [comment]
Yes, I have created a bridge in the host and linked the vm with tap interfaces to the bridge, its a more effective way than adding physical interfaces.
I think I shall close this issue for now as I await future updates.
