### ISSUE TITLE
Ping "no response found" and vm instances autoreboots

### ISSUE THREAD

**Issue by kilisio** [clownix/cloonix#5]
I am running alpine clients in cloonix with a mikrotik as gateway to test out load balancing script . The clients  keep autorebooting on their own and i can not ping public network but can access internet through browser in the clients. I have tried both debian and  arch as clients but they still autoreboot. On the matter of ping, wireshark gives error message of "no response found". I have disabled firewall on the host machine and it still times out so i figured its a cloonix thing. I am currently using version 24-01. ovs-switchd on versions prior to 24 seems to cause high cpu usage.

**Comment by clownix** [comment]
Yes the versions prior to 24 used dpdk and this leads to 100%cpu usage even if no works needs to be done.
The cloonix software tries to launch its cloonix_ssh and cloonix_scp daemon by using the qemu-guest-agent or qemu-ga that should be inside the VM. If qemu-ga is installed, cloonix assumes that it has not started correctly and reboots.
If qemu-ga is not installed inside the guest or if it wont start, then you can avoid the reboot with --no_qemu_ga at the end of the kvm start command there is the example to start the cisco which typically does not have qemu-ga inside:

PARAMS="ram=5000 cpu=4 eth=vvvv"
cloonix_cli ${NET} add kvm cisco1 ${PARAMS} ${NAME}.qcow2 --no_qemu_ga --natplug=0

Note: the VM keeps a red color with this  --no_qemu_ga option, the red means that cloonix_ssh wont work.

**Comment by clownix** [comment]
The guithub did a strange thing to the command given as example here is another shot:

cloonix_cli  nemo  add  kvm  cisco1 ram=5000  cpu=4   eth=vvvv  namebulkqcow2.qcow2  --no_qemu_ga

The --natplug=0 part is for cisco, it gives the equivalent of the cloonix_ssh (see the quickstart/cisco directory).

**Comment by kilisio** [comment]
There does not seem to be a `--no_qemu_ga` option, cloonix stops with `ERROR: --no_qemu_ga not an option`
It seems that using the `--nobackdoor` option stops the auto rebooting, but I still cannot ping out of the vm to public ip.
I think I shall close this issue for now as I await future updates. Thank you for the detailed explanation.

**Comment by clownix** [comment]
Maybe a mixup in versions, the nobackdoor seems to be an older version 
but now the current version has --no_qemu_ga...

The update of the version has to be done both for client and server.

Le 13.08.2022 09:57, kilisio a écrit :

> There does not seem to be a --no_qemu_ga option, cloonix stops with 
> ERROR: --no_qemu_ga not an option
> It seems that using the --nobackdoor option stops the auto rebooting, 
> but I still cannot ping out of the vm to public ip.
> I think I shall close this issue for now as I await future updates. 
> Thank you for the detailed explanation.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>



Links:
------
[1] https://github.com/clownix/cloonix/issues/5#issuecomment-1213955371
[2]
