### ISSUE TITLE
a2b functionality

### ISSUE THREAD

**Issue by WladimirDelaCadena** [clownix/cloonix#5]
Hello I know this element can be used to insert some traffic effects in the packets. Is it possible to use this tool? and if yes, what is the way to it. Is there any example in the demos? because I can not manage to use them. Additionally where could I find big (complex) topologies where I could use my application? Know I am experimenting with tor inside Cloonix and works well for a private lan But I would like to scale it more. Thanks

**Comment by clownix** [comment]
Try this example:
wget http://cloonix.fr/demo_stored/v-37-02/a2b.tar.gz
It is a sample of what can be done but I have not done much doc on A2B.
You will have to do the big network by yourself, I do not have one.

**Comment by WladimirDelaCadena** [comment]
Thanks a lot that is very useful.
