### ISSUE TITLE
create wifi connection from QEMU to docker

### ISSUE THREAD

**Issue by Dvergatal** [clownix/cloonix#6]
Hi all,
I am are currently working on my code written in python which creates wifi connections etc. on wlan interface and I would like to perfom tests of this code. In order to do that I have a QEMU machine which is running on docker and there is a bridge connection but I would like to establish between the docker and QEMU a wifi connection, meaning that docker is set to behave with it's virtual wlan interface as access point and QEMU as STA which is running my python code to perform wifi operations (scan for available networks, connect to it etc.)

I was reading lot of documentations about this problem and my first approach was with mininet-wifi but than I have read that in order to do that I will need to use openvswitch etc. I was woundering if it is possible to achieve with cloonix software?

**Comment by clownix** [comment]
Not possible just now but it is a good idea to add something using mac80211_hwsim to do this.
In very old versions of cloonix (10 years ago) the network was socket-based and there was an agent inside the guest that transmitted hwsim packets to another guest through the same sockets that were used for the network.
May-be it will come back into cloonix one day...

**Comment by clownix** [comment]
For the moment the wifi feature using mac80211_hwsim is not planned to be implemented.
