### ISSUE TITLE
Cannot install cloonix on Arch

### ISSUE THREAD

**Issue by iGwadaa** [clownix/cloonix#8]
**sudo ./doitall --python=/usr/bin/python2**
ERROR: Cannot use 'python', Python 2.6 or later is required.
Note that Python 3 or later is not yet supported.
Use --python=/path/to/python to specify a supported Python.

**python2 --version**
Python  2.7.14

A hundred thanks for you're amazing work dude.

**Comment by clownix** [comment]
Sorry about that, in version 39-03 it should be corrected, some compile configure have been changed. A no-reg test is currently done to check the impact on other distros.
Thanks for the issue.
