### ISSUE TITLE
Qemu unexpected error

### ISSUE THREAD

**Issue by eduardommsi** [clownix/cloonix#9]
Hi,
I installed cloonix in a  ubuntu 16.04 on a vmware but when i run your ping demo I have always the same error with the qemu-kvm virtual machines. The errors are:

-> **Error QEMU UNEXPECTED STOP two DO
 sudo cat /var/log/user.log | grep qemu**

-> **Error QEMU UNEXPECTED STOP one DO
 sudo cat /var/log/user.log | grep qemu**

->**bad endpoint start: one 0 lan1**

![captura de ecra 2018-02-27 as 10 57 41](https://user-images.githubusercontent.com/22789840/36725097-1c17b96a-1bad-11e8-9642-280af7077f75.png)

I searched for /var/log(/user.log but that file does not exist.

I´ve tried manually add a kvm with the command "**cloonix_cli nemo add kvm  clown 1000 1 2 stretch.qcow2**" but the error is the same:

-> **Error QEMU UNEXPECTED STOP clown DO
 sudo cat /var/log/user.log | grep qemu**

You have any clue to resolve this?

**Comment by clownix** [comment]
Sorry for the delay, I did not see the issue before now.
The virtualisation inside a vmware virtual machine may not work with the enable-kvm acceleration.
I use cloonix for kvm inside kvm, this is called nested virtualisation, but I have never tried kvm inside vmware.

**Comment by clownix** [comment]
https://virtuallylg.wordpress.com/2011/09/16/nested-vmware-64bit-vms-time-to-run-hyper-v-or-kvm-inside-vmware-esxi5-0-and-workstation-8-0/

**Comment by clownix** [comment]
http://thetechnologychronicle.blogspot.fr/2014/02/install-nested-kvm-in-vmware-esxi-51.html
